# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3


    - name: Run Xvfb Server
      run: |
        apt update && apt install -y wget xvfb
        Xvfb :0 -ac -screen 0 1024x768x24 &

    - name: Set Up Chromedriver
      run: |
        wget "https://chromedriver.storage.googleapis.com/110.0.5481.77/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip
        chmod +x chromedriver
        cp -ar chromedriver /usr/bin/chromedriver

    - name: Set up JDK 16
      uses: actions/setup-java@v3
      with:
        java-version: '16'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Build a package
      run: mvn package
      
    - name: List files
      run: ls -liFhR

    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: my-app-1.0-SNAPSHOT.jar
        path: target/my-app-1.0-SNAPSHOT.jar

